/**
 * Files that still carried over-limit prose comments when the 40-word cap
 * landed. The lists only shrink: once a file holds no over-limit comment,
 * its linter (the oxlint rule or the document scanner) reports the entry as
 * stale until it is pruned. Prune by deleting the path, not by rewording.
 */

export const verboseCommentScriptScope: ReadonlySet<string> = new Set([
	"drizzle.config.ts",
	"src/main/actions.ts",
	"src/main/adblock.ts",
	"src/main/bookmarks.ts",
	"src/main/commands.ts",
	"src/main/config.ts",
	"src/main/context-menu.ts",
	"src/main/db/database.ts",
	"src/main/db/schema.ts",
	"src/main/db/schema/bookmarks.ts",
	"src/main/db/schema/history.ts",
	"src/main/db/schema/session.ts",
	"src/main/db/test-database.ts",
	"src/main/db/validation.ts",
	"src/main/download-rate.ts",
	"src/main/downloads-path.ts",
	"src/main/downloads.ts",
	"src/main/error-page.ts",
	"src/main/external.ts",
	"src/main/history.ts",
	"src/main/index.ts",
	"src/main/ipc.ts",
	"src/main/local-pages.ts",
	"src/main/messages.ts",
	"src/main/omnibox.ts",
	"src/main/paths.ts",
	"src/main/permissions.ts",
	"src/main/prompts.ts",
	"src/main/session.ts",
	"src/main/stylesheet.ts",
	"src/main/tab-manager.test.ts",
	"src/main/tab-manager.ts",
	"src/main/tab.ts",
	"src/main/user-css.ts",
	"src/main/user-style-files.ts",
	"src/main/user-styles.ts",
	"src/main/vim.ts",
	"src/main/zoom.ts",
	"src/overlay/badge.ts",
	"src/preload/hints.ts",
	"src/preload/menu.ts",
	"src/preload/overlay.ts",
	"src/preload/page.ts",
	"src/renderer/App.svelte",
	"src/renderer/lib/DownloadsPanel.svelte",
	"src/renderer/lib/Omnibox.svelte",
	"src/renderer/lib/PromptLine.svelte",
	"src/renderer/lib/browser.svelte.ts",
	"src/renderer/lib/completion.svelte.ts",
	"src/renderer/lib/downloads.svelte.ts",
	"src/renderer/lib/prompts.svelte.ts",
	"src/renderer/lib/settings.svelte.ts",
	"src/shared/inject-css.ts",
	"src/shared/ipc.ts",
	"src/shared/progress.ts",
	"src/shared/url.ts",
]);

export const verboseCommentDocScope: ReadonlySet<string> = new Set([
	"src/overlay/CompletionMenu.svelte",
	"src/overlay/styles.css",
	"src/renderer/styles/panel.css",
	"src/shared/styles/menu.css",
	"src/shared/styles/tokens.css",
]);
