name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: voidzero-dev/setup-vp@v1.17.0
        with:
          node-version-file: ".node-version"
          cache: true

      - run: vp run build

      - run: vp run test
